export type Appointment = {
  id: string;
  name: string;
  phone: string;
  email?: string;
  start: Date;
  end: Date;
  startTime: string;
  endTime: string;
  status: 'confirmed' | 'waiting' | 'rescheduled' | 'canceled';
  notes?: string;
  patientId: string;
  doctorName?: string;
  specialty?: string;
  date?: string;
  time?: string;
  age:number;
  mobile?: string;
  doctorId: string; 
};
